version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - internal

  postgres:
    image: postgres:16-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Явно указываем метод аутентификации
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      # Разрешаем все подключения
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    networks:
      - internal


networks:
  internal: